
---
  - name: Config web VM with Docker
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name:  Install docker via pip
      pip:
        name: docker
        state: present
        force_apt_get: yes
    - name: Download a Docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes

